### ISSUE TITLE
Library uses human-readable title for sub-content identification

### ISSUE THREAD

**Issue by sr258** [h5p/h5p-multi-media-choice#3]
When generating the DOM elements for the media, the library checks which content type was selected by the author using the contentType property of the sub-content's metadata. Examples: https://github.com/h5p/h5p-multi-media-choice/blob/98c9ea6ca31401c00de6bfa7fbe612813dfa4dd4/src/scripts/h5p-multi-media-choice-option.js#L65-L69 and https://github.com/h5p/h5p-multi-media-choice/blob/98c9ea6ca31401c00de6bfa7fbe612813dfa4dd4/src/scripts/h5p-multi-media-choice-option.js#L77-L81

It would be safer to not use `this.media.metadata.contentType`, which is the human-readable title of the content type, but the machine readable library name in `this.media.library`. (`this.media.library.startsWith('H5P.Image ')`)

This is relevant as it prevents localization of library names. I know this is currently not available in the H5P PHP implementation, but the NodeJS implementation supports library name localization. Because of this, this content type is not compatible with it at the moment if the author uses any language other than English. Maybe Joubel wants to add library name localization to the PHP server in the future, and this issue would lead to problems then, too.

I would be willing to contribute a PR, if it is accepted after review.

**Comment by sr258** [comment]
@otacke Thanks for taking the time!

**Comment by otacke** [comment]
@sr258 Merged in now: https://github.com/h5p/h5p-multi-media-choice/pull/5
